name: Deploy SIMOC
on:
  push:
  workflow_dispatch:
    inputs:
      host:
        description: 'Deploy on this host:'
        required: true
        default: ''
      fe_branch:
        description: 'Use this frontend branch:'
        required: true
        default: 'master'
      be_branch:
        description: 'Use this backend branch:'
        required: true
        default: 'master'
      
jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      # workaround to prevent node/vite crashes during the build step
      # see https://github.com/vitejs/vite/issues/2433#issuecomment-831399876
      # assume 4GB - 512MB
      NODE_OPTIONS: '--max-old-space-size=3584'
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3
        with:
          repository: overthesun/simoc-web
          #ref: ${{ github.event.inputs.fe_branch }}
          ref: 'new-deployment'
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
      - name: Download simdata/models/skybox
        run: |
          source run.sh
      - name: npm install
        run: |
          npm install --no-fund --no-audit -g npm@latest
          npm install --no-fund
      - name: Print info
        run: |
          echo "Current branch: $GITHUB_HEAD_REF"
          echo "node $(node --version); npm $(npm --version)"
      - name: Build
        run: |
          npm run build
          ls -ld $PWD/dist/*
      - name: Upload dist folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/*
          target: /home/${{ secrets.SSH_USERNAME }}/simoc/simoc_server/dist
          rm: true
          strip_components: 1
  deploy:
    name: Deploy
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
    - name: Deploy SIMOC
      uses: appleboy/ssh-action@v0.1.10
      env:
        BE_BRANCH: 'new-deployment-3'
        DB_PASSWORD: ${{ secrets.BETA_DB_PASSWORD }}
        FLASK_SECRET: ${{ secrets.BETA_FLASK_SECRET }}
        REDIS_PASSWORD: ${{ secrets.BETA_REDIS_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BE_BRANCH,DB_PASSWORD,FLASK_SECRET,REDIS_PASSWORD
        script: |
          cd simoc
          echo "* In <`pwd`>, switching backend branch to <$BE_BRANCH>..."
          git fetch https://${{ secrets.SSH_GITHUB_USERNAME }}:${{ secrets.SSH_GITHUB_TOKEN }}@github.com/overthesun/simoc/ $BE_BRANCH:refs/remotes/origin/$BE_BRANCH
          git switch -C $BE_BRANCH origin/$BE_BRANCH --force
          echo "* Current branch is now <`git branch --show-current`>"
          echo "* Current commit is <`git show --oneline -s`>"
          python3 simoc.py --env-file=simoc_docker_beta.env deploy
